# Generated by Django 4.1.7 on 2023-03-10 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='phone',
        ),
        migrations.AddField(
            model_name='supplier',
            name='address',
            field=models.CharField(default='address', max_length=255),
        ),
        migrations.AddField(
            model_name='supplier',
            name='email',
            field=models.EmailField(default='email', max_length=255),
        ),
        migrations.AddField(
            model_name='supplier',
            name='phone_number',
            field=models.CharField(default='345345', max_length=255),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(default='name', max_length=255),
        ),
    ]
