# Generated by Django 4.1.7 on 2023-03-19 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplieruser',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
    ]
