# Generated by Django 4.1.7 on 2023-03-29 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_supplieruser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplieruser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
